#CC      = gcc
#CFLAGS  = -O3 -lwiringPi -D_POSIX_SOURCE -D_DEFAULT_SOURCE -std=c99 -Wall -Werror -Wextra -pedantic
#
#.SUFFIXES: .c .o
#
#.PHONY: all clean
#
#all: run
#
#run: 7seg.o led.o switch.o event_loop.o
#
#
#clean:
#	rm -f $(wildcard *.o)
#	rm -f run


